services:
    audio-processor:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - RESET_STATE=false
            - WHISPER_THREADS=2
            - WHISPER_COMPUTE_TYPE=int8
        volumes:
            - ./config.json:/config.json
            - ./audiobooks:/audiobooks
            - ./transcriptions:/transcriptions
            - data:/data
            - models:/models
        restart: unless-stopped

volumes:
    data:
    models:
