services:
    audio-processor:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - RESET_STATE=false
            - WHISPER_THREADS=2
        volumes:
            - ./config.json:/config.json
            - ./audiobooks:/audiobooks
            - ./data:/data
            - models:/models
            - ./transcriptions:/transcriptions
        restart: unless-stopped

volumes:
    models:
