package db

import (
	"context"
	"errors"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/pashagolub/pgxmock/v4"

	"github.com/jedwards1230/earmark/internal/patch"
)

// reviewSQL is the set of statements the REVIEWER surface (review.go) issues.
// Kept separate from corrections_test.go's correctionSQL map because these are
// this file's own package vars — the two maps are merged for the shared
// provenance guard in corrections_test.go.
var reviewSQL = map[string]string{
	"listCorrectionsSQL":        listCorrectionsSQL,
	"chunkTargetSQL":            chunkTargetSQL,
	"insertManualCorrectionSQL": insertManualCorrectionSQL,
	"markChunkStaleByIDSQL":     markChunkStaleByIDSQL,
}

// TestListCorrectionsSQL_ReadOnlyAndPristine pins the reviewer worklist query:
// read-only, and selects the PRISTINE chunk text — the same text an anchor
// must be resolved against, never the corrected surface.
func TestListCorrectionsSQL_ReadOnlyAndPristine(t *testing.T) {
	if !strings.HasPrefix(strings.TrimSpace(strings.ToUpper(listCorrectionsSQL)), "SELECT") {
		t.Errorf("listCorrectionsSQL must start with SELECT:\n%s", listCorrectionsSQL)
	}
	if !strings.Contains(listCorrectionsSQL, "COALESCE(c.source_text, c.text, '')") {
		t.Errorf("listCorrectionsSQL must select the pristine chunk text:\n%s", listCorrectionsSQL)
	}
}

// TestChunkTargetSQL_ReadOnlyAndPristine pins the direct-edit chunk read: it
// must be read-only and must select the pristine text a direct edit anchors
// against (COALESCE(c.source_text, c.text)) — Corrected (bare c.text) is
// returned too, but only for display.
func TestChunkTargetSQL_ReadOnlyAndPristine(t *testing.T) {
	if !strings.HasPrefix(strings.TrimSpace(strings.ToUpper(chunkTargetSQL)), "SELECT") {
		t.Errorf("chunkTargetSQL must start with SELECT:\n%s", chunkTargetSQL)
	}
	if !strings.Contains(chunkTargetSQL, "COALESCE(c.source_text, c.text)") {
		t.Errorf("chunkTargetSQL must select the pristine chunk text:\n%s", chunkTargetSQL)
	}
}

// TestReviewSQL_NeverTouchesTranscriptProvenance mirrors
// TestCorrectionSQL_NeverTouchesTranscriptProvenance in corrections_test.go for
// the reviewer's own four statements: none may write transcripts.segments or
// transcripts.raw_text, and none may write the transcripts table at all.
func TestReviewSQL_NeverTouchesTranscriptProvenance(t *testing.T) {
	for name, sql := range reviewSQL {
		upper := strings.ToUpper(sql)
		for _, banned := range []string{
			"UPDATE TRANSCRIPTS", "DELETE FROM TRANSCRIPTS", "INSERT INTO TRANSCRIPTS",
			"ALTER TABLE TRANSCRIPTS",
		} {
			if strings.Contains(upper, banned) {
				t.Errorf("%s must not touch transcript provenance (%q):\n%s", name, banned, sql)
			}
		}
	}
}

// TestOnlyMarkChunkStaleByIDSQLSetsEmbeddingStale asserts embedding_stale is
// written by exactly one of the four reviewer statements — the dedicated
// invalidation write — and that it never touches chunk TEXT (regenerated by
// the rebuild, never written by the reviewer).
func TestOnlyMarkChunkStaleByIDSQLSetsEmbeddingStale(t *testing.T) {
	for name, sql := range reviewSQL {
		writesFlag := strings.Contains(sql, "embedding_stale")
		if name == "markChunkStaleByIDSQL" {
			if !writesFlag {
				t.Errorf("markChunkStaleByIDSQL must set embedding_stale:\n%s", sql)
			}
			if !strings.Contains(sql, "SET embedding_stale = true") {
				t.Errorf("markChunkStaleByIDSQL must set embedding_stale = true:\n%s", sql)
			}
			continue
		}
		if writesFlag {
			t.Errorf("%s must not touch embedding_stale — only markChunkStaleByIDSQL may:\n%s", name, sql)
		}
	}
}

// TestInsertManualCorrectionSQL_InsertsFindingsWithHashGuard pins the write
// path's two load-bearing properties: it inserts into transcript_findings, and
// its WHERE clause re-hashes the chunk's CURRENT pristine text and compares it
// against the same $12 placeholder bound to the persisted chunk_text_sha256
// column — so a chunk that moved under the edit matches zero rows instead of
// silently recording against stale text.
func TestInsertManualCorrectionSQL_InsertsFindingsWithHashGuard(t *testing.T) {
	if !strings.Contains(insertManualCorrectionSQL, "INSERT INTO") ||
		!strings.Contains(insertManualCorrectionSQL, "transcript_findings") {
		t.Errorf("insertManualCorrectionSQL must insert into transcript_findings:\n%s", insertManualCorrectionSQL)
	}
	if !strings.Contains(insertManualCorrectionSQL, "sha256(") {
		t.Errorf("insertManualCorrectionSQL must re-hash the chunk's current pristine text:\n%s",
			insertManualCorrectionSQL)
	}
	if !strings.Contains(insertManualCorrectionSQL, "= $12") {
		t.Errorf("insertManualCorrectionSQL's hash guard must compare against $12:\n%s", insertManualCorrectionSQL)
	}
	// $12 must be the SAME placeholder bound to chunk_text_sha256 in the SELECT
	// list, not a coincidentally-numbered second parameter — the column list
	// ends with anchor_offset, anchor_occurrence, chunk_text_sha256, and the
	// SELECT values list ends with $10, $11, $12 in the same order.
	if !strings.Contains(insertManualCorrectionSQL, "$10, $11, $12") {
		t.Errorf("insertManualCorrectionSQL must bind chunk_text_sha256 to $12 in the SELECT list:\n%s",
			insertManualCorrectionSQL)
	}
	if strings.Count(insertManualCorrectionSQL, "chunk_text_sha256") < 1 {
		t.Errorf("insertManualCorrectionSQL must persist chunk_text_sha256:\n%s", insertManualCorrectionSQL)
	}
}

// TestListCorrections_DefaultsAndClampsLimit asserts the limit normalization:
// <= 0 falls back to the 50-row default, and anything above the 200-row
// ceiling is capped.
func TestListCorrections_DefaultsAndClampsLimit(t *testing.T) {
	tests := []struct {
		name      string
		reqLimit  int
		wantLimit int
	}{
		{"zero defaults to 50", 0, defaultCorrectionListLimit},
		{"negative defaults to 50", -5, defaultCorrectionListLimit},
		{"in-range passes through", 75, 75},
		{"above ceiling is capped at 200", 500, maxCorrectionListLimit},
		{"exactly at ceiling passes through", 200, maxCorrectionListLimit},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			database := newTestDB()
			mock, err := pgxmock.NewPool()
			if err != nil {
				t.Fatalf("new mock pool: %v", err)
			}
			defer mock.Close()

			mock.ExpectQuery("FROM transcript_findings").
				WithArgs((*string)(nil), (*string)(nil), (*string)(nil), []string(nil), 0.0, tc.wantLimit, 0).
				WillReturnRows(pgxmock.NewRows(correctionDetailColumns))

			_, err = database.listCorrections(context.Background(), mock, CorrectionFilter{Limit: tc.reqLimit})
			if err != nil {
				t.Fatalf("listCorrections: %v", err)
			}
			if err := mock.ExpectationsWereMet(); err != nil {
				t.Errorf("unmet expectations (limit not bound as %d): %v", tc.wantLimit, err)
			}
		})
	}
}

// TestListCorrections_EmptyFiltersBindNilNotEmptyString asserts the zero-value
// filter binds SQL NULL (nil) for id/path — never an empty string, which the
// query tests with `$n IS NULL` and would otherwise match nothing.
func TestListCorrections_EmptyFiltersBindNilNotEmptyString(t *testing.T) {
	database := newTestDB()
	mock, err := pgxmock.NewPool()
	if err != nil {
		t.Fatalf("new mock pool: %v", err)
	}
	defer mock.Close()

	mock.ExpectQuery("FROM transcript_findings").
		WithArgs((*string)(nil), (*string)(nil), (*string)(nil), []string(nil), 0.0,
			defaultCorrectionListLimit, 0).
		WillReturnRows(pgxmock.NewRows(correctionDetailColumns))

	_, err = database.listCorrections(context.Background(), mock, CorrectionFilter{})
	if err != nil {
		t.Fatalf("listCorrections: %v", err)
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("unmet expectations: %v", err)
	}
}

// TestListCorrections_PathBindsExactAndLikePrefix asserts a Path filter binds
// BOTH the trimmed exact path (f.file_path = $2) and its LIKE prefix
// (f.file_path LIKE $3), matching the scoped findings list / scoped clear.
func TestListCorrections_PathBindsExactAndLikePrefix(t *testing.T) {
	database := newTestDB()
	mock, err := pgxmock.NewPool()
	if err != nil {
		t.Fatalf("new mock pool: %v", err)
	}
	defer mock.Close()

	path := "/books/audio-libation/Andy Weir/Project Hail Mary"
	wantPrefix := likePrefix(path) + "/%"

	mock.ExpectQuery("FROM transcript_findings").
		WithArgs(pgxmock.AnyArg(), &path, &wantPrefix, []string(nil), 0.0, defaultCorrectionListLimit, 0).
		WillReturnRows(pgxmock.NewRows(correctionDetailColumns))

	// Trailing slash must be trimmed the same way trimPath does.
	_, err = database.listCorrections(context.Background(), mock, CorrectionFilter{Path: path + "/"})
	if err != nil {
		t.Fatalf("listCorrections: %v", err)
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("unmet expectations: %v", err)
	}
}

// correctionDetailColumns are the columns listCorrectionsSQL selects, in the
// exact order listCorrections scans them.
var correctionDetailColumns = []string{
	"id", "transcript_id", "file_path", "book_dir",
	"chunk_id", "chunk_index", "start_sec", "end_sec",
	"original_text", "suggested_correction", "issue_type", "confidence",
	"model", "origin", "patch_state", "stale_reason",
	"decided_at", "decided_by", "applied_at", "created_at",
	"anchor_offset", "anchor_occurrence", "chunk_text_sha256",
	"chunk_text",
}

// TestListCorrections_ScansRowsIncludingNullableColumns drives the real
// query + scan path against a mock pool, asserting every column lands in the
// right field — including the nullable columns via pointers.
func TestListCorrections_ScansRowsIncludingNullableColumns(t *testing.T) {
	database := newTestDB()
	mock, err := pgxmock.NewPool()
	if err != nil {
		t.Fatalf("new mock pool: %v", err)
	}
	defer mock.Close()

	chunkID := "chunk-1"
	chunkIdx := 3
	correction := "Arecibo"
	staleReason := "chunk_changed"
	decidedAt := time.Date(2026, 8, 19, 12, 0, 0, 0, time.UTC)
	decidedBy := "mcp:agent"
	appliedAt := time.Date(2026, 8, 19, 13, 0, 0, 0, time.UTC)
	createdAt := time.Date(2026, 8, 18, 10, 0, 0, 0, time.UTC)
	off, occ := 21, 0
	hash := patch.ChunkHash("the auto sebo dish")

	rows := pgxmock.NewRows(correctionDetailColumns).
		AddRow(
			"f1", "t1", "/books/a/b/ch1.m4b", "/books/a/b",
			&chunkID, &chunkIdx, 73.5, 81.0,
			"auto sebo", &correction, "misheard_proper_noun", 0.92,
			"qwen2.5-14b-instruct", OriginJudge, patch.StateProposed, &staleReason,
			&decidedAt, &decidedBy, &appliedAt, createdAt,
			&off, &occ, &hash,
			"the auto sebo dish",
		).
		// Second row exercises the NULLable columns as nil.
		AddRow(
			"f2", "t1", "/books/a/b/ch2.m4b", "/books/a/b",
			(*string)(nil), (*int)(nil), 0.0, 0.0,
			"pin name", (*string)(nil), "homophone", 0.5,
			"manual", OriginHuman, patch.StateProposed, (*string)(nil),
			(*time.Time)(nil), (*string)(nil), (*time.Time)(nil), createdAt,
			(*int)(nil), (*int)(nil), (*string)(nil),
			"",
		)

	mock.ExpectQuery("FROM transcript_findings").
		WithArgs((*string)(nil), (*string)(nil), (*string)(nil), []string(nil), 0.0,
			defaultCorrectionListLimit, 0).
		WillReturnRows(rows)

	got, err := database.listCorrections(context.Background(), mock, CorrectionFilter{})
	if err != nil {
		t.Fatalf("listCorrections: %v", err)
	}
	if len(got) != 2 {
		t.Fatalf("want 2 rows, got %d", len(got))
	}

	c0 := got[0]
	if c0.ID != "f1" || c0.TranscriptID != "t1" || c0.FilePath != "/books/a/b/ch1.m4b" || c0.BookDir != "/books/a/b" {
		t.Errorf("row 0 identity mis-scanned: %+v", c0)
	}
	if c0.ChunkID == nil || *c0.ChunkID != chunkID {
		t.Errorf("row 0 chunk id mis-scanned: %+v", c0.ChunkID)
	}
	if c0.ChunkIndex == nil || *c0.ChunkIndex != chunkIdx {
		t.Errorf("row 0 chunk index mis-scanned: %+v", c0.ChunkIndex)
	}
	if c0.SuggestedCorrection == nil || *c0.SuggestedCorrection != correction {
		t.Errorf("row 0 suggested correction mis-scanned: %+v", c0.SuggestedCorrection)
	}
	if c0.StaleReason == nil || *c0.StaleReason != staleReason {
		t.Errorf("row 0 stale reason mis-scanned: %+v", c0.StaleReason)
	}
	if c0.DecidedAt == nil || !c0.DecidedAt.Equal(decidedAt) {
		t.Errorf("row 0 decided_at mis-scanned: %+v", c0.DecidedAt)
	}
	if c0.DecidedBy == nil || *c0.DecidedBy != decidedBy {
		t.Errorf("row 0 decided_by mis-scanned: %+v", c0.DecidedBy)
	}
	if c0.AppliedAt == nil || !c0.AppliedAt.Equal(appliedAt) {
		t.Errorf("row 0 applied_at mis-scanned: %+v", c0.AppliedAt)
	}
	if !c0.CreatedAt.Equal(createdAt) {
		t.Errorf("row 0 created_at mis-scanned: %+v", c0.CreatedAt)
	}
	if c0.AnchorOffset == nil || *c0.AnchorOffset != off {
		t.Errorf("row 0 anchor offset mis-scanned: %+v", c0.AnchorOffset)
	}
	if c0.AnchorOccurrence == nil || *c0.AnchorOccurrence != occ {
		t.Errorf("row 0 anchor occurrence mis-scanned: %+v", c0.AnchorOccurrence)
	}
	if c0.ChunkTextSHA256 == nil || *c0.ChunkTextSHA256 != hash {
		t.Errorf("row 0 chunk hash mis-scanned: %+v", c0.ChunkTextSHA256)
	}
	if c0.ChunkText != "the auto sebo dish" {
		t.Errorf("row 0 chunk text mis-scanned: %q", c0.ChunkText)
	}

	c1 := got[1]
	if c1.ChunkID != nil || c1.ChunkIndex != nil || c1.SuggestedCorrection != nil ||
		c1.StaleReason != nil || c1.DecidedAt != nil || c1.DecidedBy != nil ||
		c1.AppliedAt != nil || c1.AnchorOffset != nil || c1.AnchorOccurrence != nil ||
		c1.ChunkTextSHA256 != nil {
		t.Errorf("row 1 should carry NULLs as nil pointers: %+v", c1)
	}
	if c1.ChunkText != "" {
		t.Errorf("row 1 (no chunk) should have empty chunk text, got %q", c1.ChunkText)
	}

	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("unmet expectations: %v", err)
	}
}

// TestGetChunkForEdit_HappyScan drives getChunkForEdit's query + scan path.
func TestGetChunkForEdit_HappyScan(t *testing.T) {
	database := newTestDB()
	mock, err := pgxmock.NewPool()
	if err != nil {
		t.Fatalf("new mock pool: %v", err)
	}
	defer mock.Close()

	idx := 4
	rows := pgxmock.NewRows([]string{
		"id", "transcript_id", "file_path", "chunk_index",
		"start_sec", "end_sec", "pristine", "text",
	}).AddRow("c1", "t1", "/books/a/b/ch1.m4b", idx, 240.0, 300.0,
		"He wrote under a pin name.", "He wrote under a pen name.")

	mock.ExpectQuery("FROM transcript_chunks").
		WithArgs("c1").
		WillReturnRows(rows)

	got, err := database.getChunkForEdit(context.Background(), mock, "c1")
	if err != nil {
		t.Fatalf("getChunkForEdit: %v", err)
	}
	if got.ID != "c1" || got.TranscriptID != "t1" || got.ChunkIndex != idx {
		t.Errorf("chunk identity mis-scanned: %+v", got)
	}
	if got.Pristine != "He wrote under a pin name." {
		t.Errorf("pristine mis-scanned: %q", got.Pristine)
	}
	if got.Corrected != "He wrote under a pen name." {
		t.Errorf("corrected mis-scanned: %q", got.Corrected)
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("unmet expectations: %v", err)
	}
}

// TestGetChunkForEdit_NoRowsBecomesErrChunkNotFound asserts pgx.ErrNoRows is
// translated into the package's own sentinel, so a caller can errors.Is
// against ErrChunkNotFound without knowing pgx's error type.
func TestGetChunkForEdit_NoRowsBecomesErrChunkNotFound(t *testing.T) {
	database := newTestDB()
	mock, err := pgxmock.NewPool()
	if err != nil {
		t.Fatalf("new mock pool: %v", err)
	}
	defer mock.Close()

	mock.ExpectQuery("FROM transcript_chunks").
		WithArgs("missing").
		WillReturnError(pgx.ErrNoRows)

	_, err = database.getChunkForEdit(context.Background(), mock, "missing")
	if !errors.Is(err, ErrChunkNotFound) {
		t.Fatalf("want ErrChunkNotFound, got %v", err)
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("unmet expectations: %v", err)
	}
}

// TestInsertManualCorrection_Success asserts the happy path runs the guarded
// INSERT, then the stale UPDATE, then commits — in one transaction — and
// propagates the returned id.
func TestInsertManualCorrection_Success(t *testing.T) {
	database := newTestDB()
	mock, err := pgxmock.NewPool()
	if err != nil {
		t.Fatalf("new mock pool: %v", err)
	}
	defer mock.Close()

	m := ManualCorrection{
		ChunkID: "c1", OriginalText: "auto sebo", Correction: "Arecibo",
		AnchorOffset: 21, AnchorOccurrence: 0,
		ChunkSHA256: patch.ChunkHash("the auto sebo dish"),
		IssueType:   "misheard_proper_noun", DecidedBy: "mcp:justin",
	}

	mock.ExpectBegin()
	mock.ExpectQuery("INSERT INTO transcript_findings").
		WithArgs(m.ChunkID, m.OriginalText, m.IssueType, m.Correction,
			ManualEditConfidence, ManualEditModel,
			OriginHuman, patch.StateAccepted, m.DecidedBy,
			m.AnchorOffset, m.AnchorOccurrence, m.ChunkSHA256).
		WillReturnRows(pgxmock.NewRows([]string{"id"}).AddRow("new-finding-id"))
	mock.ExpectExec("UPDATE transcript_chunks").
		WithArgs(m.ChunkID).
		WillReturnResult(pgxmock.NewResult("UPDATE", 1))
	mock.ExpectCommit()

	id, err := database.insertManualCorrection(context.Background(), mock, m)
	if err != nil {
		t.Fatalf("insertManualCorrection: %v", err)
	}
	if id != "new-finding-id" {
		t.Errorf("id: want %q, got %q", "new-finding-id", id)
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("unmet expectations: %v", err)
	}
}

// TestInsertManualCorrection_ChunkChangedRefusesWithoutStaleUpdateOrCommit
// asserts the guarded INSERT matching zero rows (pgx.ErrNoRows) is translated
// to patch.ErrChunkChanged, and that neither the stale UPDATE nor the commit
// ever run — only Begin, the failed INSERT, and the deferred Rollback.
func TestInsertManualCorrection_ChunkChangedRefusesWithoutStaleUpdateOrCommit(t *testing.T) {
	database := newTestDB()
	mock, err := pgxmock.NewPool()
	if err != nil {
		t.Fatalf("new mock pool: %v", err)
	}
	defer mock.Close()

	m := ManualCorrection{
		ChunkID: "c1", OriginalText: "auto sebo", Correction: "Arecibo",
		AnchorOffset: 21, AnchorOccurrence: 0,
		ChunkSHA256: "stale-hash-the-chunk-moved-past",
		IssueType:   "misheard_proper_noun", DecidedBy: "mcp:justin",
	}

	mock.ExpectBegin()
	mock.ExpectQuery("INSERT INTO transcript_findings").
		WithArgs(m.ChunkID, m.OriginalText, m.IssueType, m.Correction,
			ManualEditConfidence, ManualEditModel,
			OriginHuman, patch.StateAccepted, m.DecidedBy,
			m.AnchorOffset, m.AnchorOccurrence, m.ChunkSHA256).
		WillReturnError(pgx.ErrNoRows)
	mock.ExpectRollback()

	_, err = database.insertManualCorrection(context.Background(), mock, m)
	if !errors.Is(err, patch.ErrChunkChanged) {
		t.Fatalf("want patch.ErrChunkChanged, got %v", err)
	}
	// If the code had gone on to run the stale UPDATE or COMMIT, those calls
	// would have no matching expectation (only Begin/Query/Rollback are
	// registered) and ExpectationsWereMet would report the queue unmet/violated.
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("unmet expectations (stale UPDATE or commit must not have run): %v", err)
	}
}
